CC = gcc
CFLAGS = -Wall -Wextra -Iinclude -std=c99

SRC = src/main.c src/assembler.c src/symbol.c src/opcode.c
OBJ = $(SRC:.c=.o)
TARGET = sicxeasm

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJ) $(TARGET)